FROM php:7.0-fpm

RUN docker-php-ext-install pdo pdo_mysql mysqli \
    && pecl install -o -f xdebug \
    && rm -rf /tmp/pear \
    && echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20121212/xdebug.so" > /usr/local/etc/php/conf.d/xdebug.ini \